[build]
 publish = ".next"
  functions = "functions"   # dossier o√π sont tes fonctions
  command = "set NEXT_DISABLE_ESLINT=1 && npm run build"



[[redirects]]
  from = "/fritokpartage.html"
  to = "/share/:videoId"
  query = { videoId = ":videoId", ref = ":ref", token = ":token" }
  status = 200



