[build]
  command = "npm run build"
  publish = ".next"
  functions = "functions"   # dossier o√π sont tes fonctions

[[redirects]]
  from = "/fritokpartage.html"
  to = "/share/:videoId"
  query = { videoId = ":videoId", ref = ":ref", token = ":token" }
  status = 200



