[build]
  command = "npm run build"
  publish = ".next"   # ou "out" si tu utilises `next export`
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
command = "npm run dev"
port = 8888      # port où Netlify Dev écoute
framework = "next"


# ✅ Redirections pour gérer les routes dynamiques
[[redirects]]
  from = "/share/:videoId"
  to = "/.netlify/functions/share"
  status = 200
  force = true
